name: Test Project

on: push # Poderíamos escolher até em qual branch vamos executar, neste caso esta executando em qualquer branch.

jobs: # no plural sempre
  first-job:

    runs-on: ubuntu-latest
    steps:

      - name: Get Code # Fazer o download do código
        uses: actions/checkout@v4
        # O bloco abaixo recebe as configurações necessárias para execução
        # Peguei alguns parâmetros default só para mostrar como poderíamos referenciar um valor a ser passado e como apontar
        with:
            # Não precisar passar nada abaixo, é mostrei para ver como usamos valores das quais o actions tem acesso.
            repository: ${{ github.repository }} # Este é o default
            token: ${{ github.token }} # Este é o default
    
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Test NodeJS Version
        run: node --version

      - name: Install dependênces
        run: npm ci # também instala as dependências mas é mais seguro do que o npm install

      - name: Run Tests 
        run: npm test # Nem esse